name: Windows x64 VST3 Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:

    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Check compiler
        shell: cmd
        run: |
          where cl
          cl

      - name: Clean build
        shell: cmd
        run: |
          if exist build rmdir /s /q build

      - name: Configure CMake
        shell: cmd
        run: |
          cmake -S . -B build -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        shell: cmd
        run: |
          cmake --build build --parallel

      - name: Upload VST3
        uses: actions/upload-artifact@v4
        with:
          name: Windows-x64-VST3
          path: |
            build/**/*.vst3
